# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import file
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setStyleSheet("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 585))
        self.label.setStyleSheet("background-color: rgb(218, 176, 255);\n"
"border-radius:20px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../../Desktop/3949372.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(130, 90, 570, 420))
        self.frame.setStyleSheet("QFrame\n"
"{\n"
"background-color: transparent;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(210, 0, 360, 420))
        self.frame_2.setToolTipDuration(0)
        self.frame_2.setStyleSheet("QFrame{\n"
"background:rgba(255,255,255,0.8);\n"
"border-style: outset;\n"
"border-top-right-radius: 25px;\n"
"border-bottom-right-radius: 25px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(0, 20, 361, 66))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(48)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"\n"
"font: 75 48pt \"Gabriola\";\n"
"color: rgb(0,0,0);\n"
"background:transparent;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.logbtn = QtWidgets.QPushButton(self.frame_2)
        self.logbtn.setGeometry(QtCore.QRect(60, 280, 221, 41))
        self.logbtn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 16pt \"Gabriola\";\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-color: rgb(138, 64, 234);\n"
"     \n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(150, 70, 255);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(109, 50, 185);\n"
"    }\n"
"\n"
"")
        self.logbtn.setAutoDefault(False)
        self.logbtn.setDefault(True)
        self.logbtn.setObjectName("logbtn")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 350, 221, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("background:rgba(0,0,0,0);\n"
"color: rgb(0,0,0);\n"
"font: 10pt \"Georgia\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    font: 10pt \"Gabriola\";\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background-color: rgba(180, 37, 232, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(198, 40, 255);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(132, 26, 170);\n"
"    }\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.name = QtWidgets.QLineEdit(self.frame_2)
        self.name.setGeometry(QtCore.QRect(90, 120, 201, 31))
        self.name.setToolTipDuration(-1)
        self.name.setStyleSheet("QLineEdit\n"
"{\n"
"font: 14pt \"Segoe UI\";\n"
"border: 2px solid rgb(138, 64, 234);\n"
"border-radius: 15px; \n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"background:rgba(255,255,255,0.5);\n"
"color: rgb(0,0,0);\n"
"}\n"
"QLineEdit:hover\n"
"{\n"
"    border: 1px solid rgb(138, 64, 234);\n"
"    font: 18pt \"High Tower Text\";\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(138, 64, 234);\n"
"    background:rgba(255,255,255,0.8);\n"
"}\n"
"")
        self.name.setText("")
        self.name.setCursorPosition(0)
        self.name.setObjectName("name")
        self.password = QtWidgets.QLineEdit(self.frame_2)
        self.password.setGeometry(QtCore.QRect(90, 200, 201, 31))
        self.password.setStyleSheet("QLineEdit\n"
"{\n"
"font: 14pt \"Segoe UI\";\n"
"border: 2px solid rgb(138, 64, 234);\n"
"border-radius: 15px; \n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"background:rgba(255,255,255,0.5);\n"
"color: rgb(0,0,0);\n"
"}\n"
"QLineEdit:hover\n"
"{\n"
"    border: 1px solid rgb(138, 64, 234);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(138, 64, 234);\n"
"    background:rgba(255,255,255,0.8);\n"
"}\n"
"")
        self.password.setText("")
        self.password.setObjectName("password")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(40, 120, 31, 31))
        self.label_4.setStyleSheet("background:rgba(0,0,0,0);\n"
" background-image: url(:/usedicon/images/used_icons/user.png);\n"
"    background-repeat: no-reperat;\n"
"    background-position: center;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/icons/24x24/cil-user.png"))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(40, 200, 31, 31))
        self.label_7.setStyleSheet("background:rgba(0,0,0,0);\n"
" background-image: url(:/usedicon/images/used_icons/password.png);\n"
"    background-repeat: no-reperat;\n"
"    background-position: center;")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/newPrefix/icons/24x24/cil-https.png"))
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 240, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    font: 11pt \"Gabriola\";\n"
"    border-style: outset;\n"
"    background-color: Transparent;\n"
"    }\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: Transparent;\n"
"    }\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 210, 420))
        self.frame_3.setStyleSheet("background:rgba(255,255,255,0.5);\n"
"border-style: outset;\n"
"border-top-left-radius: 25px;\n"
"border-bottom-left-radius: 25px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 201, 200))
        self.label_5.setStyleSheet("background:rgba(0,0,0,0);\n"
" background-image: url(:/usedicon/images/used_icons/logo.ico);\n"
"    background-repeat: no-reperat;\n"
"    background-position: center;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Logo.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 800, 40))
        self.frame_4.setStyleSheet("background-color: transparent;\n"
"\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.buttons_frame = QtWidgets.QFrame(self.frame_4)
        self.buttons_frame.setGeometry(QtCore.QRect(740, 0, 60, 40))
        self.buttons_frame.setMaximumSize(QtCore.QSize(100, 40))
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_frame.setObjectName("buttons_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.buttons_frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.close = QtWidgets.QPushButton(self.buttons_frame)
        self.close.setMaximumSize(QtCore.QSize(20, 20))
        self.close.setStyleSheet("QPushButton {\n"
"    background-image: url(:/usedicon/images/used_icons/x.png);\n"
"    background-repeat: no-reperat;\n"
"    background-position: center;\n"
"    border-style: outset;\n"
"    background-color: rgb(234, 0, 0);\n"
"    border-radius:10px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(168, 0, 0)\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color:rgb(195, 0, 0)\n"
"    }")
        self.close.setText("")
        self.close.setObjectName("close")
        self.horizontalLayout_9.addWidget(self.close)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Log in"))
        self.logbtn.setText(_translate("Dialog", "LOGIN"))
        self.label_6.setText(_translate("Dialog", "Don\'t have an account ?"))
        self.pushButton.setText(_translate("Dialog", "SIGN IN"))
        self.name.setPlaceholderText(_translate("Dialog", "Username"))
        self.password.setPlaceholderText(_translate("Dialog", "Password"))
        self.pushButton_2.setText(_translate("Dialog", "Forgot Password ?"))
        self.close.setToolTip(_translate("Dialog", "close"))

