# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'message.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import file
from PyQt5 import QtCore, QtGui, QtWidgets


class messages(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(375, 190)
        Dialog.setMaximumSize(QtCore.QSize(375, 190))
        Dialog.setStyleSheet("background-color: Transparent;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainframe = QtWidgets.QFrame(Dialog)
        self.mainframe.setMaximumSize(QtCore.QSize(375, 190))
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainframe)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.mainframe)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setStyleSheet("    background-color: rgba(180, 37, 232, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-top-right-radius:10px;\n"
"border-top-left-radius:10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.close = QtWidgets.QPushButton(self.frame)
        self.close.setGeometry(QtCore.QRect(345, 5, 20, 20))
        self.close.setMinimumSize(QtCore.QSize(20, 20))
        self.close.setMaximumSize(QtCore.QSize(20, 20))
        self.close.setStyleSheet("QPushButton {\n"
"     background-image: url(:/usedicon/images/used_icons/x.png);\n"
"    background-repeat: no-reperat;\n"
"    background-position: center;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background-color: rgb(235, 0, 0);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(168, 0, 0)\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color:rgb(234, 0, 0)\n"
"    }")
        self.close.setText("")
        self.close.setObjectName("close")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(55, 5, 160, 22))
        self.label_3.setMinimumSize(QtCore.QSize(160, 20))
        self.label_3.setMaximumSize(QtCore.QSize(160, 22))
        self.label_3.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.icon = QtWidgets.QPushButton(self.frame)
        self.icon.setGeometry(QtCore.QRect(10, 0, 28, 28))
        self.icon.setMinimumSize(QtCore.QSize(28, 28))
        self.icon.setMaximumSize(QtCore.QSize(28, 28))
        self.icon.setToolTip("")
        self.icon.setStyleSheet("QPushButton {\n"
"     background-image: url(:/usedicon/images/used_icons/messaging.png);\n"
"    background-repeat: no-reperat;\n"
"    background-position: center;\n"
"    border-style: outset;\n"
"    }")
        self.icon.setText("")
        self.icon.setObjectName("icon")
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.mainframe)
        self.frame_2.setStyleSheet("background-color: rgb(255,255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setStyleSheet("    background-repeat: no-reperat;\n"
"    background-position: center;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(240, 60))
        self.label_2.setAcceptDrops(False)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.label_2.setText("")
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.mainframe)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setStyleSheet("    background-color: rgb(218, 176, 255);\n"
"border-bottom-right-radius:10px;\n"
"border-bottom-left-radius:10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushpushpush = QtWidgets.QPushButton(self.frame_3)
        self.pushpushpush.setGeometry(QtCore.QRect(280, 10, 75, 23))
        self.pushpushpush.setStyleSheet("\n"
"QPushButton\n"
"{background-color: rgb(255, 255, 255);\n"
"color:rgb(138, 64, 234);\n"
"border-radius:10px;\n"
"font: 75 12pt \'High Tower Text\'; }\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color:rgb(232, 182, 0);\n"
"    }")
        self.pushpushpush.setObjectName("pushpushpush")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.mainframe)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.close.setToolTip(_translate("Dialog", "close"))
        self.pushpushpush.setText(_translate("Dialog", "OK"))

