# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import file
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_splash(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(Dialog)
        self.dropShadowFrame.setStyleSheet("QFrame {    \n"
"    background-color: rgb(218, 176, 255);\n"
"\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dropShadowFrame)
        self.verticalLayout.setContentsMargins(0, 40, 0, 2)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.dropShadowFrame)
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(40)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("    border: none;\n"
"  background-image: url(:/usedicon/images/used_icons/logo.ico);\n"
"    background-repeat: no-reperat;\n"
"    background-position: center;\n"
"    background-color: transparent;")
        self.label_title.setText("")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.label_description = QtWidgets.QLabel(self.dropShadowFrame)
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(18)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.verticalLayout.addWidget(self.label_description)
        self.label_loading = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_loading.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet(" color: rgb(0,0,0);")
        self.label_loading.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_loading.setObjectName("label_loading")
        self.verticalLayout.addWidget(self.label_loading)
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 4))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(218, 176, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border-style: none;\n"
"    border-radius: 2px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255,255,255);\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.progressBar.raise_()
        self.label_loading.raise_()
        self.label_description.raise_()
        self.label_title.raise_()
        self.horizontalLayout.addWidget(self.dropShadowFrame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_description.setText(_translate("Dialog", "<strong>APP</strong> DESCRIPTION"))
        self.label_loading.setText(_translate("Dialog", " Loading Expense Monitor..."))

